# tmux configuration file
# ManuelR, jan2024

# set color
set -g default-terminal "screen-256color"
#set -g default-terminal "xterm-256color"
set-option -sa terminal-overrides ",xterm*Tc"

# action key
set-option -g repeat-time 0
set-option -g focus-events on

# change split panels
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# reload tmux conf
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

# Open current directory

# Detectar si estamos en WSL, Mac o Linux puro
#if-shell "uname -r | grep -q 'microsoft'" \
#    "bind o run-shell 'explorer.exe .'" \
#    "if-shell 'uname | grep -q Darwin' \
#        'bind o run-shell \"open #{pane_current_path}\"' \
#        'bind o run-shell \"xdg-open #{pane_current_path}\"'"

# prefijo + e, cierra todos los paneles menos en el que estoy
bind -r e kill-pane -a

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window


# basic settings (https://github.com/craftzdog/dotfiles-public/blob/master/.config/tmux/tmux.conf)

set-option -g status-justify "left"
#set-option utf8-default on
#set-option -g mouse-select-pane
#set-window-option -g mode-keys vi
#set-window-option -g utf8 on
# look'n feel
#set-option -g status-fg cyan
#set-option -g status-bg black
#set -g pane-active-border-style fg=colour166,bg=default
#set -g window-style fg=colour10,bg=default
#set -g window-active-style fg=colour12,bg=default

set-option -g history-limit 64096
set -sg escape-time 10


# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
set -g set-titles-string "#T"


# status bar, thanks http://zanshin.net/2013/09/05/my-tmux-configuration/
# for the sweet colors.
#set -g status-interval 3
#set-option -g status-bg colour237
#set-option -g status-fg white
#set-option -g status-attr dim 
#set-window-option -g window-status-fg brightblue #base0
#set-window-option -g window-status-bg colour236 
#set-window-option -g window-status-attr dim
#set -g status-left ' #S ::'
#set -g status-right ' #(uptime | egrep -o "[0-9]+ users?, +load.*" | sed "s/ averages//"), %H:%M '
#set-window-option -g window-status-current-fg brightred #orange
#set-window-option -g window-status-current-bg colour236 
#set-window-option -g window-status-current-attr bright

# revisar tmux.conf de pelado (youtube)

# import
source ~/.config/tmux/utility.conf
